export const cardSets = [
  "Valiant Smashers",
  "Age of Overlord",
  "25th Anniversary Tin: Dueling Heroes Mega Pack",
  "Legendary Duelists: Soulburning Volcano",
  "Duelist Nexus",
  "Battles of Legend: Monstrous Revenge",
  "Wild Survivors",
  "Cyberstorm Access",
  "Maze of Memories",
  "Photon Hypernova",
  "Amazing Defenders",
  "Battles of Legend: Crystal Revenge",
  "Darkwing Blast",
  "2022 Tin of Pharaoh's Gods Mega Pack",
  "Tactical Masters",
  "Power of the Elements",
  "Legendary Duelist: Season 3",
  "Legendary Duelist: Duels From the Deep",
  "Dimension Force",
  "Ghosts From the Past: The 2nd Haunting",
  "Hidden Arsenal: Chapter 1",
  "Battle of Chaos Booster Pack",
  "The Grand Creators",
  "Brothers of Legend",
  "Burst of Destiny",
  "Legendary Duelist: Synchro Storm",
  "Dawn of Majesty",
  "King's Court",
  "Lightning Overdrive",
  "Ancient Guardians",
];

export const sortables = ["type", "level"];
